### ISSUE TITLE
is this even compatible to mac os x ?

### ISSUE THREAD

**Issue by beboeverbebo** [wiire/pixiewps#11]
Hey,

Sorry if the question seems anyway rude the problem i have been trying for good part of day reading articles, forum post to install this my macbook  pro osx 10.9.5 ,but i keep hitting a dead end.

Among my failures are apt-get and yum they don't seem respond to the commands long after configuring and installing them.

                                                                                                                                            --help , please?!!

**Comment by wiire** [comment]
Download pixiewps and follow the installation instructions in the [README](https://github.com/wiire/pixiewps/blob/master/README.md) file. Should compile and install fine now (6471952) on Mac OS.

**Comment by beboeverbebo** [comment]
i'm also having trouble getting apt-get to download the libssl, any advice on that ?

**Comment by soxrok2212** [comment]
Mac OS X does not have apt-get. You have to manually install it

**Comment by beboeverbebo** [comment]
and from where should i get the necessary files?, there is quite a lot on the web ,but i don't know where to start

**Comment by beboeverbebo** [comment]
thank you!

**Comment by beboeverbebo** [comment]
i finished installing openssl now how do i use it install libssl-dev, tried googling got no clear answer..

**Comment by soxrok2212** [comment]
I think you should be all set. Keep in mind you need to install pixiewps with sudo or under su.

**Comment by beboeverbebo** [comment]
yeah i no that and thank you got it to install big help , thanks again! :) :+1: :100:
