### ISSUE TITLE
Plz tell what to do if pin not found and router is vulnerable

### ISSUE THREAD

**Issue by Kaushalrocks** [wiire/pixiewps#12]
i searched but no results found for router D link 600m which i have at home 
i tested done bruteforce but no showing pin
wiire plz help as u told u will come up with fix in august
plzzzzzzzzzzzzzzz

**Comment by soxrok2212** [comment]
You should be happy that 'your' router isn't vulnerable :)

**Comment by wiire** [comment]
If you get:

> [!] The AP /might be/ vulnerable. Try again with --force or with another (newer) set of data.

it doesn't mean it's vulnerable, just, it might be. The chipset that device has is currently not supported.
