### ISSUE TITLE
Can we get a new release?

### ISSUE THREAD

**Issue by fbettag** [wiire/pixiewps#16]
I'd very much like to submit my FreeBSD port for pixiewps. If we can get a new release-version (say 1.2), i'd hold off on submitting until then.

Since you haven't pushed a new tag since May, this might be a good time :)

Thanks in advance for considering

**Comment by wiire** [comment]
Yes. I'm currently developing version __1.2__, which adds more features, help and fixes bug https://github.com/wiire/pixiewps/issues/14. I had to rewrite the core part and make more tests so it's taking some time. Plus I don't have much free time at the moment.

If everything goes as planned I should release it in a couple of weeks or so.

Thank you.

**Comment by d8tahead** [comment]
Yes, very busy

https://youtu.be/y7epl0pKTAE

**Comment by soxrok2212** [comment]
Much appreciated d8tahead, the video helps a lot.

**Comment by wiire** [comment]
@fbettag 
New release added for version [1.2.1](https://github.com/wiire/pixiewps/releases/tag/v1.2.1). There were still a few bugs. Sorry for the late updates.

**Comment by fbettag** [comment]
thank you! Happy 2016! I already submitted an updated freebsd port for this :)
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=205870
