### ISSUE TITLE
searching the keyspace with --force requires -e nonce?

### ISSUE THREAD

**Issue by ichrispa** [wiire/pixiewps#17]
Hi wiire,

When users are redirected to using --force ("AP might be vulnerable"), the option will apparently not take effect unless an e-none is passed (line 334 and 369 in pixiewps.c). This makes sense given that the parameters detected by reaver are required to bruteforce the key space, but it is not documented and very confusing given that the e-nonce is stated as being optional.

Also, pixiewps stop the key search after about 2 seconds when --force is passed. It would be incredibly helpful to get feedback as to why. Could this be implemented?

Cheers,

ichrispa

**Comment by wiire** [comment]
> When users are redirected to using --force ("AP might be vulnerable"), the option will apparently not take effect unless e-nonce is passed.

That is correct, the Enrollee nonce is used as a reference to recover the state of the PRNG.

> This makes sense given that the parameters detected by reaver are required to bruteforce the key space

I don't understand what you're trying to say here. The parameters (data) needed change depending on the mode / type of PRNG. The enrollee nonce is required for almost all of them...

> but it is not documented and very confusing given that the e-nonce is stated as being optional.

... except one, this is the reason why it's been made optional. It's always "good" to specify e-nonce even when it's not strictly necessary though, as the usage examples show (if you don't know exactly what you are targenting). I know it may be confusing. I will probably make it mandatory or explain it better on the new release, see https://github.com/wiire/pixiewps/issues/16.

>  pixiewps stop the key search after about 2 seconds when --force is passed

If this happens after the "AP might be vulnerable" warning, then see https://github.com/wiire/pixiewps/issues/14. This happens essentially when M1 and M3 are generated with in a 1.5s (on avarage) time gap (min. 1s - max 2s). This is more likely to happen if you are using a "slow device" (both AP and / or end device).

**Comment by ichrispa** [comment]
Hi @wiire,

most of my questions got settled, especially since the documentation issue is handled in #16.

>> pixiewps stop the key search after about 2 seconds when --force is passed

> If this happens after the "AP might be vulnerable" warning, then see #14. This happens essentially when M1 and M3 are generated within a 1.5s (on avarage) time gap (min. 1s - max 2s). This is more likely to happen if you are using a "slow device" (both AP and / or end device).

I found that my issue is actually related to line 379 when mode 4 is reached:

     /* Checks if the sequence may actually be generated by current random function */
     if (wps->e_nonce[0] < 0x80 && wps->e_nonce[4] < 0x80 && wps->e_nonce[8] < 0x80  && wps->e_nonce[12] < 0x80) {

The enrollee nonce simply does not match the condition and brute force is (silently) skipped. Again feedback would be nice here. So as far as I can see there is no bug/issue here and #14 does not apply? If so, feel free to close the issue.

Again thanks for you help wiire.

Regards,

ichrispa

**Comment by wiire** [comment]
If you don't get the "AP might be vulnerable" message withouth `--force`. Then the AP __is not__ vulnerable.

If you take a look at the code:

```C
/* Checks if the sequence may actually be generated by current random function */
if (wps->e_nonce[0] < 0x80 && wps->e_nonce[4] < 0x80 && wps->e_nonce[8] < 0x80  && wps->e_nonce[12] < 0x80) {

    valid = true;

...


if (!found && mode == 4 && valid && !wps->bruteforce) {
    printf(" [!] The AP /might be/ vulnerable. Try again with --force or with another (newer) set of data.\n\n");
}
```

The *boolean* valid is set only if the nonce "matches a certain pattern".

Also if it's vulnerable then the PKe should start with: D0:14:1B:15:65:6E:96:B8: ... (althought this check is not present in the code).

**Comment by ichrispa** [comment]
OK, that settle's it for me.

Thank you for your support wiire.
