### ISSUE TITLE
Installing problem

### ISSUE THREAD

**Issue by casperass** [wiire/pixiewps#2]
I can't install pixiewps. I get this error when I type "make" in its src directory.

gcc -o pixiewps pixiewps.c -lssl -lcrypto -Wall -Werror
pixiewps.c:33:26: fatal error: openssl/hmac.h: No such file or directory
compilation terminated.
make: * [all] Error 1

I'm using the latest version.

**Comment by leto** [comment]
Looks like you need to install openssl header files and/or use the appropriate environment variable to point gcc towards them.

**Comment by wiire** [comment]
Did you 'sudo apt-get install libssl-dev'?

**Comment by wiire** [comment]
No more replies from OP. Closed.

**Comment by wilmax10** [comment]
I have a similar problem, I installed: sudo apt-get install libssl-dev , sudo apt-get install libpcap-dev aircrack-ng sqlite3 libsqlite3-dev .I also used: sudo apt-get update . I'm using Ubuntu 14.10 on VirtualBox I also tried using Kali Linux but anything works :(  gcc -std=c99 -o pixiewps pixiewps.c random_r.c -lssl -lcrypto
In file included from pixiewps.c:51:0:
pixiewps.h:66:25: fatal error: openssl/sha.h: No such file or directory
 #include <openssl/sha.h>
                         ^
compilation terminated.
Makefile:10: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by Attila15** [comment]
help

**Comment by Attila15** [comment]
help, no gcc
