### ISSUE TITLE
Missing 1.2 github version tag.

### ISSUE THREAD

**Issue by Techwolf** [wiire/pixiewps#20]
This commit, https://github.com/wiire/pixiewps/commit/32091e45eea4d0e287cf3ff339f4f905d18753f8 says updated to 1.2, but I notice there is no tag for that release.

**Comment by wiire** [comment]
Yes but I'd rather wait a few days and fix all the issues that will arise with this new changes before creating a tag. The new version can be compiled and run on wide variety of platforms Linux(Ubuntu, Debian ...), *BSD, Mac OS X, Windows (with MinGW), OpenWrt, Android ... so I expect to be some issues with some for I can personally test only on a few of those.

**Comment by wiire** [comment]
@Techwolf 
New release added for version [1.2.1](https://github.com/wiire/pixiewps/releases/tag/v1.2.1). There were still a few bugs. Sorry for the late updates.

**Comment by Techwolf** [comment]
No problem. I'me just now updating my gentoo overlay and found an bug and opened an issue already.
