### ISSUE TITLE
Division by zero warning, might be a fluke

### ISSUE THREAD

**Issue by fbettag** [wiire/pixiewps#21]
FreeBSD compile reports this warning:
```
gmake[1]: Entering directory '/wrkdirs/usr/ports/security/pixiewps/work/pixiewps-1.2.1/src'
cc -std=c99 -O3 -o pixiewps pixiewps.c random_r.c crypto/sha256.c crypto/md.c crypto/md_wrap.c
pixiewps.c:790:52: warning: division by zero is undefined [-Wdivision-by-zero]
        unsigned long long ms_elapsed = (c_end - c_start) / (CLOCKS_PER_SEC / 1000);
```
I know it's not critical, but other than that, all compiler warnings from clang are gone :+1:

**Comment by wiire** [comment]
Before adding the tag I compiled the program with Clang on Mac OS X so I thought everything was fine...

The problem here is that under FreeBSD, CLOCKS_PER_SEC = 128, leading to a division by zero. 

Source: http://bugs.vcmi.eu/view.php?id=719

**Comment by fbettag** [comment]
Can you fix it and push another release tag? I'd update the port then to have this fixed as well.

**Comment by wiire** [comment]
I will look later today. I'm not at my compiling station right now.

Thank you testing and happy new year to you as well :)

**Comment by mazagan** [comment]
HI. I'm from morrocco . thank you for that program .please i'f you have any idea for attack  technicolor v 3 wps activated with pixiewps

**Comment by wiire** [comment]
@fbettag 
It should be fixed now. I used `gettimeofday()` instead of `clock()` from (`time.h`).

Tested again on Ubuntu 32 bit (GCC), Mac OS X 64 bit (Clang) and Windows 64 bit (with MinGW). No errors or warnings (using `-Wall` `-Wextra`).

**Comment by fbettag** [comment]
seems fixed now :) can we get another release? :)

**Comment by fbettag** [comment]
Well the only thing that stands out:
cc -std=c99 -O3 -Wall -Wextra -DDEBUG -o pixiewps pixiewps.c random_r.c crypto/sha256.c crypto/md.c crypto/md_wrap.c
In file included from pixiewps.c:32:
./pixiewps.h:220:13: warning: comparison of integers of different signs: 'char' and 'unsigned int' [-Wsign-compare]
                if (*list <= (max_digit + '0')) {
                    ~~~~~ ^   ~~~~~~~~~~~~~~~
1 warning generated.

**Comment by wiire** [comment]
Mind testing again? Possibly with `-Wall` and `-Wextra`. If everything's good I'll push another tag.

**Comment by fbettag** [comment]
cc -std=c99 -O3 -Wall -Wextra -DDEBUG -o pixiewps pixiewps.c random_r.c crypto/sha256.c crypto/md.c crypto/md_wrap.c
<done> :)

looks good now

**Comment by wiire** [comment]
Pushed new tag [1.2.2](https://github.com/wiire/pixiewps/releases/tag/v1.2.2).

Thank you again, much appreciated.

**Comment by fbettag** [comment]
Submitted to FreeBSD https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=205870 :)

No worries, thanks for doing the code, i just package :)
