### ISSUE TITLE
makefile bug: $(DESTDIR) used twice in install.

### ISSUE THREAD

**Issue by Techwolf** [wiire/pixiewps#22]
From src/Makefile:

PREFIX = $(DESTDIR)/usr
LOCDIR = $(PREFIX)/local/bin

install -m 755 $(TARGET) $(DESTDIR)$(LOCDIR) evals to this on my system:
install -m 755 pixiewps /var/tmp/portage/net-wireless/pixiewps-1.2.2/image//var/tmp/portage/net-wireless/pixiewps-1.2.2/image//usr/local/bin

As you can see from the above, $(DESTDIR) is used twice.

**Comment by wiire** [comment]
On every platform I tested $(DESTDIR) is equal to "" so I didn't notice. I don't think I will push another tag unless more issues pops out. Let me know if everything's good now.

Thank you.

**Comment by Techwolf** [comment]
Looks good so far. Just need to test when I get some free time. Only other issue is I need to test if "make LOCDIR=<whatever I set it here> install" so my ebuild can set the install of the bin to /usr/bin. If it fails, I'll open another issue with a suggested fix.

**Comment by wiire** [comment]
Ok. I'll close this issue for now.

**Comment by blshkv** [comment]
@Techwolf FYI, we are maintaining that ebuild in Pentoo Linux. You are welcome to use it too
https://github.com/pentoo/pentoo-overlay/commit/835ebec1e678570c3ac2fef398a3037c1b77e4ee
