### ISSUE TITLE
Pin not found!

### ISSUE THREAD

**Issue by whitecjohn** [wiire/pixiewps#26]
`root@kali:~# pixiewps -e bf:b4:1d:a6:e4:d8:17:f2:80:0a:88:66:48:62:ea:6c:07:0b:e5:91:53:c0:59:3b:e2:a7:28:8e:50:d7:77:b0:17:21:18:6e:02:18:f0:76:e1:bc:44:70:31:eb:20:85:fd:17:1e:25:14:99:a3:93:f5:90:bc:b4:69:3e:3f:a5:9b:c5:4e:7e:7a:24:2f:e2:fa:0a:77:d7:9b:d6:ad:df:1e:77:ab:6e:f3:29:15:4f:68:b4:c4:6c:9e:e7:16:f6:db:c0:6b:df:a4:38:79:31:32:0d:2a:ca:07:be:66:6f:da:0f:a8:f1:90:40:db:15:1b:c9:52:74:59:88:cb:7b:95:29:f9:55:1a:c2:96:3c:1b:2d:b1:92:c7:e4:af:c3:36:66:a7:23:78:08:9b:99:18:8a:32:c7:b5:39:8c:db:09:d1:bf:2f:eb:30:f7:dd:80:f9:3b:7a:74:16:c7:34:2a:2c:e8:b2:0c:52:c9:fd:0c:8c:10:c5:28:a6:c1:a7 -r d5:a3:69:92:a8:4f:d5:ca:42:a8:eb:f8:6e:90:22:57:12:42:93:69:a9:1d:ac:82:63:62:88:85:4c:77:05:7f:82:cc:1d:1a:00:b1:05:ae:9b:b4:cb:21:59:72:63:aa:78:92:fa:96:a3:97:b7:ad:15:94:56:3b:c0:13:20:08:5c:69:36:da:c6:74:6e:ba:76:e4:56:22:a3:09:fb:5b:06:29:a9:58:6a:e5:60:b8:51:b9:f8:0e:67:89:c2:1a:f8:5e:a7:d2:35:67:3d:f7:ab:23:e0:e1:18:d8:7a:be:3e:39:e2:86:16:3f:70:20:8f:69:3f:65:aa:fd:8d:c0:90:58:9b:c9:aa:1b:29:78:53:df:53:71:6a:b3:ac:d7:80:83:32:4d:9f:ef:91:c1:7e:97:d6:f7:bb:9a:92:3d:46:20:5a:b5:69:ce:3a:62:50:99:6c:09:ad:73:54:56:f0:c4:0e:77:21:32:79:5e:50:61:c7:03:bd:c0:44:f4 -s 8a:e2:db:1e:23:6f:4f:3c:7f:97:75:ce:12:b4:35:0f:ba:e3:07:74:4f:fe:f3:3c:ff:65:64:81:68:7e:23:57 -z c9:9a:85:f3:51:7a:1a:45:9b:dd:49:52:23:4e:e6:84:0c:98:80:23:a1:e2:5d:97:bf:b5:92:27:2a:88:27:86 -a 81:20:10:0a:f7:ea:ac:df:2e:04:fe:cc:63:d9:72:34:52:2c:8c:6d:f5:d8:83:17:b9:02:ea:a8:3b:4f:81:15 -n 14:ad:7e:70:11:31:73:41:2f:a3:ca:dc:37:fd:ef:d8 -m 94:b8:19:d1:f7:72:35:c6:b0:a7:81:cf:32:b4:be:e2

 Pixiewps 1.2

 [-] WPS pin not found!

 [*] Time taken: 0 s 421 ms

 [!] The AP /might be/ vulnerable. Try again with --force or with another (newer) set of data.

real	0m0.424s
user	0m0.424s
sys	0m0.000s
`

after trying this command :  
`root@kali:~# bully -b DC:53:7C:1D:12:75 -c 11  -v 4  wlan1mon -d
[!] Bully v1.1 - WPS vulnerability assessment utility
[P] Modified for pixiewps by AAnarchYY(aanarchyy@gmail.com)
[+] Switching interface 'wlan1mon' to channel '11'
[!] Using '00:c0:ca:81:a2:f9' for the source MAC address
[+] Datalink type set to '127', radiotap headers present
[+] Scanning for beacon from 'dc:53:7c:1d:12:75' on channel '11'
[+] Got beacon for 'TC-E08BF' (dc:53:7c:1d:12:75)
[!] Beacon information element indicates WPS is locked
[+] Loading randomized pins from '/root/.bully/pins'
[!] Restoring session from '/root/.bully/dc537c1d1275.run'
[+] Index of starting pin number is '0002000'
[+] Last State = 'NoAssoc'   Next pin '37914929'
[!] WPS lockout reported, sleeping for 43 seconds ...
[+] Rx(Beacon) = 'Timeout'   Next pin '37914929'
[+] Sent packet not acknowledged after 3 attempts
[+] Tx( Strt ) = 'Timeout'   Next pin '37914929'
[+] Sent packet not acknowledged after 3 attempts
[+] Tx(DeAuth) = 'Timeout'   Next pin '37914929'
[P] ENonce: 14:ad:7e:70:11:31:73:41:2f:a3:ca:dc:37:fd:ef:d8
[P] PKE: bf:b4:1d:a6:e4:d8:17:f2:80:0a:88:66:48:62:ea:6c:07:0b:e5:91:53:c0:59:3b:e2:a7:28:8e:50:d7:77:b0:17:21:18:6e:02:18:f0:76:e1:bc:44:70:31:eb:20:85:fd:17:1e:25:14:99:a3:93:f5:90:bc:b4:69:3e:3f:a5:9b:c5:4e:7e:7a:24:2f:e2:fa:0a:77:d7:9b:d6:ad:df:1e:77:ab:6e:f3:29:15:4f:68:b4:c4:6c:9e:e7:16:f6:db:c0:6b:df:a4:38:79:31:32:0d:2a:ca:07:be:66:6f:da:0f:a8:f1:90:40:db:15:1b:c9:52:74:59:88:cb:7b:95:29:f9:55:1a:c2:96:3c:1b:2d:b1:92:c7:e4:af:c3:36:66:a7:23:78:08:9b:99:18:8a:32:c7:b5:39:8c:db:09:d1:bf:2f:eb:30:f7:dd:80:f9:3b:7a:74:16:c7:34:2a:2c:e8:b2:0c:52:c9:fd:0c:8c:10:c5:28:a6:c1:a7
[P] WPS Manufacturer: CBN
[P] WPS Model Name: CH7284
[P] WPS Model Number: 123456
[P] WPS Serial Number: 0000001
[P] RNonce: 94:b8:19:d1:f7:72:35:c6:b0:a7:81:cf:32:b4:be:e2
[P] PKR: d5:a3:69:92:a8:4f:d5:ca:42:a8:eb:f8:6e:90:22:57:12:42:93:69:a9:1d:ac:82:63:62:88:85:4c:77:05:7f:82:cc:1d:1a:00:b1:05:ae:9b:b4:cb:21:59:72:63:aa:78:92:fa:96:a3:97:b7:ad:15:94:56:3b:c0:13:20:08:5c:69:36:da:c6:74:6e:ba:76:e4:56:22:a3:09:fb:5b:06:29:a9:58:6a:e5:60:b8:51:b9:f8:0e:67:89:c2:1a:f8:5e:a7:d2:35:67:3d:f7:ab:23:e0:e1:18:d8:7a:be:3e:39:e2:86:16:3f:70:20:8f:69:3f:65:aa:fd:8d:c0:90:58:9b:c9:aa:1b:29:78:53:df:53:71:6a:b3:ac:d7:80:83:32:4d:9f:ef:91:c1:7e:97:d6:f7:bb:9a:92:3d:46:20:5a:b5:69:ce:3a:62:50:99:6c:09:ad:73:54:56:f0:c4:0e:77:21:32:79:5e:50:61:c7:03:bd:c0:44:f4
[P] Authkey: 81:20:10:0a:f7:ea:ac:df:2e:04:fe:cc:63:d9:72:34:52:2c:8c:6d:f5:d8:83:17:b9:02:ea:a8:3b:4f:81:15
[P] E-Hash1: 8a:e2:db:1e:23:6f:4f:3c:7f:97:75:ce:12:b4:35:0f:ba:e3:07:74:4f:fe:f3:3c:ff:65:64:81:68:7e:23:57
[P] E-Hash2: c9:9a:85:f3:51:7a:1a:45:9b:dd:49:52:23:4e:e6:84:0c:98:80:23:a1:e2:5d:97:bf:b5:92:27:2a:88:27:86
`

Help?

**Comment by annat83** [comment]
Hi. Same here:
--------------------------------------------------
Pixiewps 1.2
 [-] WPS pin not found!
[*] Time taken: 0 s 172 ms
-------------------------------------------------
Already try all  Optional Arguments Variations ...

Linux Mint 17.3
TP-WN722N

Attacking at:
WPS Manufacturer: TP-LINK     WPS Model Name: TL-WR940N

More Details on AP:
PWR  Beacons    #Data,    #/s   CH  MB     ENC      CIPHER      AUTH         
-----------------------------------------------------------------------------------------------
 -79       42                0        0      11  54e.    WPA2    CCMP         PSK  

Cheers!

**Comment by wiire** [comment]
Due to #25 I reverted back some changes about the check on vulnerable models. This means that there could be some false positives (maybe between 10 and 25%).

The warning clearly states: *[!] The AP __/might be/__ vulnerable*. Which means it's not to be taken for granted.

Pixiewps should not be thought as a "passepartout".
