### ISSUE TITLE
When I `make`, the `make: *** No rule to make target '/package.mk'.  Stop.`

### ISSUE THREAD

**Issue by lizhenguo** [wiire/pixiewps#27]
The `make` output:
>Makefile:1: /rules.mk: No such file or directory
Makefile:7: /package.mk: No such file or directory
make: *** No rule to make target '/package.mk'.  Stop.

My operating system is `Linux 4.4.0-22-generic #39-Ubuntu SMP Thu May 5 16:53:32 UTC 2016 GNU/Linux`, and `Ubuntu 16.04 LTS`, what's the problem when I make?

**Comment by lizhenguo** [comment]
I have found the problem.

**Comment by lemiere** [comment]
so what ? share please!

**Comment by shark0der** [comment]
For @lemiere and any future wanderer: `cd src` before `make`

**Comment by omeros21** [comment]
Checking 'ldconfig-stub'... failed.

Build dependency: Failed to install stub

Prerequisite check failed. Use FORCE=1 to override.
gmake: *** [/home/omeros/openwrt/include/toplevel.mk:180: staging_dir/host/.prereq-build] Error 1
what's the problem ? how can I solve this?

**Comment by rofl0r** [comment]
use the provided makefile, not the openwrt one.
