### ISSUE TITLE
broken Makefile

### ISSUE THREAD

**Issue by blshkv** [wiire/pixiewps#28]
sorry, I'm lazy to fork it. Here is the patch:

```
--- Makefile.orig       2016-01-05 06:08:02.000000000 +0800
+++ Makefile    2016-05-25 13:41:02.008984971 +0800
@@ -3,9 +3,8 @@
 TARGET = pixiewps
 CRYPTO = crypto/sha256.c crypto/md.c crypto/md_wrap.c
 SOURCE = $(TARGET).c random_r.c $(CRYPTO)
-PREFIX = $(DESTDIR)/usr
+PREFIX = /usr/local
 BINDIR = $(PREFIX)/bin
-LOCDIR = $(PREFIX)/local/bin
 
 all:
        $(CC) $(CCFLAGS) -o $(TARGET) $(SOURCE)
@@ -14,10 +13,8 @@
        $(CC) $(CCFLAGS) -DDEBUG -o $(TARGET) $(SOURCE)
 
 install:
-       rm -f $(BINDIR)/$(TARGET)
-       rm -f $(LOCDIR)/$(TARGET)
-       install -d $(DESTDIR)$(LOCDIR)
-       install -m 755 $(TARGET) $(DESTDIR)$(LOCDIR)
+       install -d $(DESTDIR)$(BINDIR)
+       install -m 755 $(TARGET) $(DESTDIR)$(BINDIR)
 
 uninstall:
        rm $(BINDIR)/$(TARGET)
```

**Comment by wiire** [comment]
What's exactly _broken_? Which platform are you using? Some comments would be helpful.

Old versions of the program where installed in `/usr/bin`, thus the `rm -f $(BINDIR)/$(TARGET)`.

**Comment by blshkv** [comment]
The current logic just does not make any sense. The LOCDIR is basically the BINDIR. BINDIR is not in use (well, it used  in the "uninstall" section only). You also delete files during installation which is not common.
At the end, you confused yourself and use $(DESTDIR)/$(DESTDIR) twice during installation. It was picked up by portage (Gentoo) because it installs everything in a sandbox.

My patch revert the logic back to orthodox way.

**Comment by wiire** [comment]
>you confused yourself and use $(DESTDIR)/$(DESTDIR) twice during installation

You're looking at the wrong (old) Makefile, see #22.

`LOCDIR` is `/usr/local/bin` (**new** installation directory)
`BINDIR` is `/usr/bin` (old installation directory)

Usually `/usr/bin` is prioritized over `/usr/local/bin`. If I don't make it remove the old version from `/usr/bin`, the system will always pick up the old version.

**Comment by blshkv** [comment]
yes you are right, I was looking at the release, not the latest git.

But the logic is still kind of broken in the latest too. The main purpose of PREFIX is to specify either /usr/local or any other location. And serves as prefix for bin, share, etc.

Oh well, as long as it works..
