### ISSUE TITLE
Add openssl exception to your GPL license

### ISSUE THREAD

**Issue by sbrun** [wiire/pixiewps#3]
Hello,
the openssl license is not compatible with the GPL. You need to grant a special exception allowing users to link your GPL application with the openssl library. See for instance the following URLs:
https://people.gnome.org/~markmc/openssl-and-the-gpl
https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/#license-specification

thanks

**Comment by wiire** [comment]
Updated license with OpenSSL exemption.

**Comment by wiire** [comment]
Added license file. Closed.
