### ISSUE TITLE
last hope pixiewps attack but also failed.

### ISSUE THREAD

**Issue by mahmoodalam62** [wiire/pixiewps#34]
Congratulations. I have Successfully wasted 10 days. Pixiewps also failed. What the f*** is this?
![kali 7](https://cloud.githubusercontent.com/assets/23416871/20237649/b9e44d28-a88d-11e6-824a-f775da58bfa6.jpg)

**Comment by kcdtv** [comment]
Swearing and having such an attitude won't solve your problems :hankey: 
If in ten days you are not able to understand what is going here than you should definitely dedicate yourself to something else. 
That is the only sensible thing to tell you.

**Comment by soxrok2212** [comment]
Well said @kcdtv

**Comment by KiUserExceptionDispatcher** [comment]
It's time to go to school :)
