### ISSUE TITLE
Anyone know about Dumpper

### ISSUE THREAD

**Issue by mahmoodalam62** [wiire/pixiewps#35]
Please tell me anyone about Dumpper v.80.9. Does it gives the correct wps pin or its just a joke. 
![kali8](https://cloud.githubusercontent.com/assets/23416871/20237689/b2ca5176-a88e-11e6-9487-98834ac55ec1.jpg)

**Comment by soxrok2212** [comment]
This has nothing to do with pixiewps. Please stop flaming all over the internet.

**Comment by wiire** [comment]
Unrelated.
