### ISSUE TITLE
Using pixiewps on wep network

### ISSUE THREAD

**Issue by slipklouco** [wiire/pixiewps#37]
Hello guys
I can use the application in the network with wep.
Remembering that they have active wps.

Thank you.

**Comment by soxrok2212** [comment]
This is not an issue?

**Comment by slipklouco** [comment]
I do not know.

**Comment by soxrok2212** [comment]
Please remove this issue.

**Comment by slipklouco** [comment]
ok brother

**Comment by wiire** [comment]
The standard doesn't allow WPS for WEP networks. Some non-certified APs may have it enabled or only marked it as enabled. There's no way of knowing the behavior until you actually try.
