### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by wpa2** [wiire/pixiewps#38]
Bug in src/Makefile, lines 17 and 18

17	install -d $(DESTDIR)$(BINDIR)
18	install -m 755 $(TARGET) $(DESTDIR)$(BINDIR)

BINDIR already includes DESTDIR, because BINDIR includes RPEFIX and PREFIX includes DESTDIR:

6	PREFIX ?= $(DESTDIR)/usr
7	BINDIR = $(PREFIX)/bin

so the result is as follows:
	install -d $(DESTDIR)$(DESTDIR)/usr/bin

Fix it please.

**Comment by wpa2** [comment]
I created a Pull request with corrections.

**Comment by wiire** [comment]
Applied. Thank you.
