### ISSUE TITLE
It doesn't give E-Hash1 and E-Hash2 

### ISSUE THREAD

**Issue by casperass** [wiire/pixiewps#4]
When do I type "reaver -i mon0 -c x -b xxxxx -vv -S" It gives me pke and the auth key but it doesn't give E-Hash1 and E-Hash2.

It was succesfully trying pins when I was using reaver 1.4. I tried it on 10 AP's and It says " WPS transaction failed (code: 0x03), re-trying last pin" so doesn't give E-Hash1 and E-Hash2. I waited 15 minutes to try a pin successfully but didn't work.

**Comment by wiire** [comment]
This is not about pixiewps. Closed.
