### ISSUE TITLE
Implementation on Wemos D1 mini pro

### ISSUE THREAD

**Issue by nisc3** [wiire/pixiewps#40]
Is it possible to implement on esp8266 chip? Wemos D1 mini pro got 16MB of storage, supports monitor mode, has an external antenna connector, supports packet injection, it can be programmed through arduino IDE.

**Comment by wiire** [comment]
I don't have that board but I do have a few simple ESP8266 modules. Last time I checked injection and monitor mode support weren't fully implemented, but rather some kind of rudimental semi-working hacks. I had my hopes up for the newer ESP32 module.

**Comment by nisc3** [comment]
I came across this repo https://github.com/spacehuhn/esp8266_deauther
Both packet injection and monitor mode works fine. Is it possible to develop pixiewps? Any limitations?

**Comment by doge27** [comment]
I can provide you with few Wemos, if you like to develop pixiewps for esp8266...

**Comment by wiire** [comment]
While full-featured packet injection seems possibile with an older SDK, monitor mode doesn't seem to be a viable option:

http://www.esp8266.com/viewtopic.php?f=6&t=1589
http://www.esp8266.com/viewtopic.php?f=8&t=12288

The buffer for packet reception seems to be limited to 128 bytes, which means that packets get cut to the first 128 bytes, as I understand it.

Those programs that use 'monitor mode' are extracting  only a few fields from the first 128 bytes of the packets like SSID, BSSID etc.

**Comment by nisc3** [comment]
It is possible to develop pixiewps if we are able to recieve the complete raw packets?

**Comment by nisc3** [comment]
https://m.aliexpress.com/s/item/32717596730.html
Don't know whether this thing support packet injection...

**Comment by wiire** [comment]
I would suggest looking for a small wireless router supported by [OpenWrt](https://wiki.openwrt.org/toh/start) / [LEDE](https://lede-project.org/supported_devices) if all you want is a small portable device.
