### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by ferchorama** [wiire/pixiewps#43]
Hi, I'm using  Kali Linux 2016.2, I'm trying to install v1.1 of pixiewps and getting error as follows:
```

root@pegasus:~/Downloads/pixiewps-1.1/src# make
gcc -std=c99 -o pixiewps pixiewps.c random_r.c -lssl -lcrypto
In file included from pixiewps.c:51:0:
pixiewps.h: In function ‘hmac_sha256’:
pixiewps.h:138:11: error: storage size of ‘ctx’ isn’t known
  HMAC_CTX ctx;
           ^~~
pixiewps.h:139:2: warning: implicit declaration of function ‘HMAC_CTX_init’ [-Wimplicit-function-declaration]
  HMAC_CTX_init(&ctx);
  ^~~~~~~~~~~~~
pixiewps.h:143:2: warning: implicit declaration of function ‘HMAC_CTX_cleanup’ [-Wimplicit-function-declaration]
  HMAC_CTX_cleanup(&ctx);
  ^~~~~~~~~~~~~~~~
Makefile:10: recipe for target 'all' failed
make: *** [all] Error 1

```

Can you help? Am I doing something wrong please?

**Comment by wiire** [comment]
README: _Prior versions of 1.2 require libssl-dev_

`sudo apt-get update && apt-get install libssl-dev`

**Comment by ferchorama** [comment]
Oh! Thank you very much! I did what you proposed and I'm still getting error:
```

root@pegasus:~/Downloads/pixiewps-1.1/src# make
gcc -std=c99 -o pixiewps pixiewps.c random_r.c -lssl -lcrypto
In file included from pixiewps.c:51:0:
pixiewps.h: In function ‘hmac_sha256’:
pixiewps.h:138:11: error: storage size of ‘ctx’ isn’t known
  HMAC_CTX ctx;
           ^~~
pixiewps.h:139:2: warning: implicit declaration of function ‘HMAC_CTX_init’ [-Wimplicit-function-declaration]
  HMAC_CTX_init(&ctx);
  ^~~~~~~~~~~~~
pixiewps.h:143:2: warning: implicit declaration of function ‘HMAC_CTX_cleanup’ [-Wimplicit-function-declaration]
  HMAC_CTX_cleanup(&ctx);
  ^~~~~~~~~~~~~~~~
Makefile:10: recipe for target 'all' failed
make: *** [all] Error 1

```

**Comment by wiire** [comment]
I think it's the same issue: https://github.com/aanarchyy/bully/issues/10

__lloydXmas__ said:
> It's probably due to API changes in newer versions of openssl that cause the compile to fail. What version of openssl are you running? openssl version -v

> If you only have something like 1.1.0 then you probably also have the libssl 1.1 development libraries which cause these errors. You can check your library version with ldconfig:
ldconfig -p | grep libssl

> If you only see libssl.so.1.1 try:
apt-get install libssl1.0-dev

**Comment by wiire** [comment]
To make things more clear:

Version **1.1** requires `libssl1.0-dev`. Installing `libssl-dev` on **Debian** (and derivatives such as *Kali Linux*) will get you the latest version (> 1.0) which breaks compatibility.

As a reference:
https://github.com/aircrack-ng/aircrack-ng/commit/6c1a38328c512031dbf515d90ce6f43fc408ad92

Changed API:
https://github.com/aircrack-ng/aircrack-ng/commit/9a1846507ff043c397257206ff21adae90a122f4

**Comment by kcdtv** [comment]
in actualized kali the issue is not solve by installing libssl-dev (at least with **version 1.1**) 
it is solved by installing **libssl1.0-dev** and that will remove **libssl-dev**

```
Nota, seleccionando «libssl1.0-dev» para la expresión regular «ibssl1.0-dev»
El paquete indicado a continuación se instaló de forma automática y ya no es necesario.
  libssl-doc
Utilice «apt autoremove» para eliminarlo.
Los siguientes paquetes se ELIMINARÁN:
  libssl-dev
Se instalarán los siguientes paquetes NUEVOS:
  libssl1.0-dev
```
