### ISSUE TITLE
OpenWrt Makefile?

### ISSUE THREAD

**Issue by mile18** [wiire/pixiewps#44]
Hi there,
could you please put the Makefile for the OpenWrt becouse i'm having problem with writing it.
Thank you in advance.

**Comment by Yukariin** [comment]
Isn't it OpenWrt matter to deal with their own build system?

**Comment by mile18** [comment]
it is, but if you say that you can compile it on openwrt it would be nice to include makefile with it, like t6x included with reaver-wps-fork-t6x

**Comment by wiire** [comment]
It's already been included in the root folder since almost two years now (571f5a5): [pixiewps/Makefile](https://github.com/wiire/pixiewps/blob/master/Makefile)

I've successfully compiled it for OpenWrt AA (12.09) and CC (15.05).

**Comment by mile18** [comment]
wow, that was fast :D thank you once more!
