### ISSUE TITLE
RTL819x and  Small DH keys

### ISSUE THREAD

**Issue by 1yura** [wiire/pixiewps#45]
Hello wiire! Can you explain please why you are blocking the RTL819x algorithm for Small DH keys?
>if (wps->small_dh_keys || check_small_dh_keys(wps->pkr)) {
...
	snprintf(wps->warning, 256, " [!] Small DH keys is not supported for mode %u!\n\n", RTL819x);

**Comment by wiire** [comment]
Simply because it doesn't work with small keys. It never has and nobody really knows why.

**Comment by 1yura** [comment]
Thank you.

**Comment by wiire-a** [comment]
@1yura 
An old question

> it turns out the library used to compute the cryptographic keys, specifically the big number library, is potentially bugged on some devices and may cause weird behaviors.

**Comment by wiire-a** [comment]
@1yura 
An old question but here's the answer:

> [...] it turns out the library used to compute the cryptographic keys, specifically the big number library, is potentially bugged on some devices and may cause weird behaviors [...]

> [...] some won't even be able to validate the correct PIN and the transaction will fail after M4. For this reason this feature is deprecated and should never be used in Reaver.

Pixiewps may still be able to recover the PIN in some cases, but it's better not to use it altogether.
