### ISSUE TITLE
deprecated? doesn't work on the latest mac OS version? i am on 10.10.3

### ISSUE THREAD

**Issue by shaunstanislaus** [wiire/pixiewps#8]
shaunstanislaus@Master ~/openssl-1.0.2a/pixiewps/src (master) $ make
cc -std=c99 -O3 -o pixiewps pixiewps.c random_r.c -lcrypto -I../include
In file included from pixiewps.c:55:
./pixiewps.h:130:2: warning: 'SHA256_Init' is deprecated: first deprecated in OS X 10.7 [-Wdeprecated-declarations]
        SHA256_Init(&ctx);
        ^
/usr/include/openssl/sha.h:147:5: note: 'SHA256_Init' has been explicitly marked deprecated here
int SHA256_Init(SHA256_CTX *c) DEPRECATED_IN_MAC_OS_X_VERSION_10_7_AND_LATER;
    ^
In file included from pixiewps.c:55:
./pixiewps.h:131:2: warning: 'SHA256_Update' is deprecated: first deprecated in OS X 10.7 [-Wdeprecated-declarations]
        SHA256_Update(&ctx, data, data_len);
        ^
/usr/include/openssl/sha.h:148:5: note: 'SHA256_Update' has been explicitly marked deprecated here
int SHA256_Update(SHA256_CTX *c, const void *data, size_t len) DEPRECATED_IN_MAC_OS_X_VERSION_10_7_AND_LATER;
    ^
In file included from pixiewps.c:55:
./pixiewps.h:132:2: warning: 'SHA256_Final' is deprecated: first deprecated in OS X 10.7 [-Wdeprecated-declarations]
        SHA256_Final(digest, &ctx);
        ^
/usr/include/openssl/sha.h:149:5: note: 'SHA256_Final' has been explicitly marked deprecated here
int SHA256_Final(unsigned char *md, SHA256_CTX *c) DEPRECATED_IN_MAC_OS_X_VERSION_10_7_AND_LATER;
    ^
In file included from pixiewps.c:55:
./pixiewps.h:139:2: warning: 'HMAC_CTX_init' is deprecated: first deprecated in OS X 10.7 [-Wdeprecated-declarations]
        HMAC_CTX_init(&ctx);
        ^
/usr/include/openssl/hmac.h:90:6: note: 'HMAC_CTX_init' has been explicitly marked deprecated here
void HMAC_CTX_init(HMAC_CTX *ctx) DEPRECATED_IN_MAC_OS_X_VERSION_10_7_AND_LATER;
     ^
In file included from pixiewps.c:55:
./pixiewps.h:140:2: warning: 'HMAC_Init_ex' is deprecated: first deprecated in OS X 10.7 [-Wdeprecated-declarations]
        HMAC_Init_ex(&ctx, key, key_len, EVP_sha256(), 0);
        ^
/usr/include/openssl/hmac.h:97:6: note: 'HMAC_Init_ex' has been explicitly marked deprecated here
void HMAC_Init_ex(HMAC_CTX *ctx, const void *key, int len,
     ^
In file included from pixiewps.c:55:
./pixiewps.h:140:35: warning: 'EVP_sha256' is deprecated: first deprecated in OS X 10.7 [-Wdeprecated-declarations]
        HMAC_Init_ex(&ctx, key, key_len, EVP_sha256(), 0);
                                         ^
/usr/include/openssl/evp.h:673:15: note: 'EVP_sha256' has been explicitly marked deprecated here
const EVP_MD *EVP_sha256(void) DEPRECATED_IN_MAC_OS_X_VERSION_10_7_AND_LATER;
              ^
In file included from pixiewps.c:55:
./pixiewps.h:141:2: warning: 'HMAC_Update' is deprecated: first deprecated in OS X 10.7 [-Wdeprecated-declarations]
        HMAC_Update(&ctx, data, data_len);
        ^
/usr/include/openssl/hmac.h:99:6: note: 'HMAC_Update' has been explicitly marked deprecated here
void HMAC_Update(HMAC_CTX *ctx, const unsigned char *data, size_t len) DEPRECATED_IN_MAC_OS_X_VERSION_10_7_AND_LATER;
     ^
In file included from pixiewps.c:55:
./pixiewps.h:142:2: warning: 'HMAC_Final' is deprecated: first deprecated in OS X 10.7 [-Wdeprecated-declarations]
        HMAC_Final(&ctx, digest, &h_len);
        ^
/usr/include/openssl/hmac.h:100:6: note: 'HMAC_Final' has been explicitly marked deprecated here
void HMAC_Final(HMAC_CTX *ctx, unsigned char *md, unsigned int *len) DEPRECATED_IN_MAC_OS_X_VERSION_10_7_AND_LATER;
     ^
In file included from pixiewps.c:55:
./pixiewps.h:143:2: warning: 'HMAC_CTX_cleanup' is deprecated: first deprecated in OS X 10.7 [-Wdeprecated-declarations]
        HMAC_CTX_cleanup(&ctx);
        ^
/usr/include/openssl/hmac.h:91:6: note: 'HMAC_CTX_cleanup' has been explicitly marked deprecated here
void HMAC_CTX_cleanup(HMAC_CTX *ctx) DEPRECATED_IN_MAC_OS_X_VERSION_10_7_AND_LATER;
     ^
9 warnings generated.

**Comment by wiire** [comment]
It seems that Apple is migrating from OpenSSL to Common Crypto. As a result the OpenSSL API is marked as "deprecated" from OS X 10.7.

I added -Wno-error=deprecated-declarations. Let me know if works for you.

**Comment by Rnewbie** [comment]
As of July 3, I also receive the same message too. Help is greatly appreciated. 

```cc -std=c99 -O3 -Wno-error=deprecated-declarations -o pixiewps pixiewps.c -lcrypto -I../include
In file included from pixiewps.c:55:
./pixiewps.h:130:2: warning: 'SHA256_Init' is deprecated: first deprecated in OS
      X 10.7 [-Wdeprecated-declarations]
        SHA256_Init(&ctx);
        ^
/usr/include/openssl/sha.h:147:5: note: 'SHA256_Init' has been explicitly marked
      deprecated here
int SHA256_Init(SHA256_CTX *c) DEPRECATED_IN_MAC_OS_X_VERSION_10_7_AND_LATER;
    ^
In file included from pixiewps.c:55:
./pixiewps.h:131:2: warning: 'SHA256_Update' is deprecated: first deprecated in
      OS X 10.7 [-Wdeprecated-declarations]
        SHA256_Update(&ctx, data, data_len);
        ^
/usr/include/openssl/sha.h:148:5: note: 'SHA256_Update' has been explicitly
      marked deprecated here
int SHA256_Update(SHA256_CTX *c, const void *data, size_t len) DEPRECATE...
    ^
In file included from pixiewps.c:55:
./pixiewps.h:132:2: warning: 'SHA256_Final' is deprecated: first deprecated in
      OS X 10.7 [-Wdeprecated-declarations]
        SHA256_Final(digest, &ctx);
        ^
/usr/include/openssl/sha.h:149:5: note: 'SHA256_Final' has been explicitly
      marked deprecated here
int SHA256_Final(unsigned char *md, SHA256_CTX *c) DEPRECATED_IN_MAC_OS_...
    ^
In file included from pixiewps.c:55:
./pixiewps.h:139:2: warning: 'HMAC_CTX_init' is deprecated: first deprecated in
      OS X 10.7 [-Wdeprecated-declarations]
        HMAC_CTX_init(&ctx);
        ^
/usr/include/openssl/hmac.h:90:6: note: 'HMAC_CTX_init' has been explicitly
      marked deprecated here
void HMAC_CTX_init(HMAC_CTX *ctx) DEPRECATED_IN_MAC_OS_X_VERSION_10_7_AND_LATER;
     ^
In file included from pixiewps.c:55:
./pixiewps.h:140:2: warning: 'HMAC_Init_ex' is deprecated: first deprecated in
      OS X 10.7 [-Wdeprecated-declarations]
        HMAC_Init_ex(&ctx, key, key_len, EVP_sha256(), 0);
        ^
/usr/include/openssl/hmac.h:97:6: note: 'HMAC_Init_ex' has been explicitly
      marked deprecated here
void HMAC_Init_ex(HMAC_CTX *ctx, const void *key, int len,
     ^
In file included from pixiewps.c:55:
./pixiewps.h:140:35: warning: 'EVP_sha256' is deprecated: first deprecated in OS
      X 10.7 [-Wdeprecated-declarations]
        HMAC_Init_ex(&ctx, key, key_len, EVP_sha256(), 0);
                                         ^
/usr/include/openssl/evp.h:673:15: note: 'EVP_sha256' has been explicitly marked
      deprecated here
const EVP_MD *EVP_sha256(void) DEPRECATED_IN_MAC_OS_X_VERSION_10_7_AND_LATER;
              ^
In file included from pixiewps.c:55:
./pixiewps.h:141:2: warning: 'HMAC_Update' is deprecated: first deprecated in OS
      X 10.7 [-Wdeprecated-declarations]
        HMAC_Update(&ctx, data, data_len);
        ^
/usr/include/openssl/hmac.h:99:6: note: 'HMAC_Update' has been explicitly marked
      deprecated here
void HMAC_Update(HMAC_CTX *ctx, const unsigned char *data, size_t len) D...
     ^
In file included from pixiewps.c:55:
./pixiewps.h:142:2: warning: 'HMAC_Final' is deprecated: first deprecated in OS
      X 10.7 [-Wdeprecated-declarations]
        HMAC_Final(&ctx, digest, &h_len);
        ^
/usr/include/openssl/hmac.h:100:6: note: 'HMAC_Final' has been explicitly marked
      deprecated here
void HMAC_Final(HMAC_CTX *ctx, unsigned char *md, unsigned int *len) DEP...
     ^
In file included from pixiewps.c:55:
./pixiewps.h:143:2: warning: 'HMAC_CTX_cleanup' is deprecated: first deprecated
      in OS X 10.7 [-Wdeprecated-declarations]
        HMAC_CTX_cleanup(&ctx);
        ^
/usr/include/openssl/hmac.h:91:6: note: 'HMAC_CTX_cleanup' has been explicitly
      marked deprecated here
void HMAC_CTX_cleanup(HMAC_CTX *ctx) DEPRECATED_IN_MAC_OS_X_VERSION_10_7...
     ^
9 warnings generated.
Undefined symbols for architecture x86_64:
  "_initstate_r", referenced from:
      _main in pixiewps-938967.o
  "_random_r", referenced from:
      _main in pixiewps-938967.o
  "_srandom_r", referenced from:
      _main in pixiewps-938967.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [all] Error 1```

**Comment by wiire** [comment]
@Rnewbie now should compile despite the errors 6471952.

**Comment by Talone** [comment]
@wiire I get error 71 - 'Operation not permitted' on 'sudo make install'

$ sudo make
cc -std=c99 -O3 -Wno-deprecated-declarations -o pixiewps pixiewps.c random_r.c -lcrypto
$ sudo make install
rm -f /usr/local/bin/pixiewps
install pixiewps /usr/bin/pixiewps
install: /usr/bin/pixiewps: Operation not permitted
make: *** [install] Error 71
