### ISSUE TITLE
Mac OS X Yosemite

### ISSUE THREAD

**Issue by fachos** [wiire/pixiewps#9]
Hi... i'm on yosemite.. i have successfully compile n test,
but i have to run from the folder i downloaded.. it not in the /bin path.. 
Here the issue after sudo make install

"
install -D pixiewps /usr/bin/pixiewps
install: illegal option -- D
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
Makefile:12: recipe for target 'install' failed
"

Unfortunately there was no reaver 1.5.2 from t6x can run in os x,
can't get any pkr,pke,hash etc..
i still having error  while ./configure --> ./iwlib.h:54:10: fatal error: 'linux/types.h'

thank you

**Comment by soxrok2212** [comment]
To view all the pixie dust stuff, you need to use -vvv in your command. This has just been changed in the latest version to clean things up a bit :)

**Comment by fachos** [comment]
Here the path i run from
XXX-Pro:src XXX-INC$ pwd
/users/XXX-INC/Downloads/pixiewps-master/src

Pixiewps 1.1 WPS pixie dust attack tool
 Copyright (c) 2015, wiire <wi7ire@gmail.com>

 Usage: ./pixiewps <arguments>

 Required Arguments:

    -e, --pke           : Enrollee public key
    -r, --pkr           : Registrar public key
    -s, --e-hash1       : Enrollee Hash1
    -z, --e-hash2       : Enrollee Hash2
    -a, --authkey       : Authentication session key

 Optional Arguments:

    -n, --e-nonce       : Enrollee nonce
    -m, --r-nonce       : Registrar nonce
    -b, --e-bssid       : Enrollee BSSID
    -S, --dh-small      : Small Diffie-Hellman keys (PKr not needed)   [No]
    -f, --force         : Bruteforce the whole keyspace                [No]
    -v, --verbosity     : Verbosity level 1-3, 1 is quietest            [3]

    -h, --help          : Display this usage screen

 Examples:

 pixiewps -e <pke> -r <pkr> -s <e-hash1> -z <e-hash2> -a <authkey> -n <e-nonce>
 pixiewps -e <pke> -s <e-hash1> -z <e-hash2> -a <authkey> -n <e-nonce> -S
 pixiewps -e <pke> -s <e-hash1> -z <e-hash2> -n <e-nonce> -m <r-nonce> -b <e-bssid> -S


Nevermind, i was tinking you gonna fix the installation path...
make easier for others... i just mv the file to /usr/bin/ done...
i did email you asking some favor, have you received?
